name: check
on:
  workflow_run:
    workflows: [prepare]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    container:
      image: docker_image:ol9
    steps:
      - name: test
        run: echo "test"
      - name: Check clang-format
        run: find . -type f -regex '.*\\.\\(hpp\\|cpp\\)$' -print0 | xargs -0 clang-format --dry-run --Werror --style=file"
