name: prepare

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  docker-image-ol9: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build $DOCKER_OPTS -t docker_image:ol9 --build-arg OS_DISTRO=oraclelinux --build-arg OS_RELEASE=9 -f docker/Dockerfile .

  check:
    runs-on: ubuntu-latest
    container:
      image: docker_image:ol9
    needs: docker-image-ol9
    steps:
      - name: Check clang-format
        run: find . -type f -regex '.*\\.\\(hpp\\|cpp\\)$' -print0 | xargs -0 clang-format --dry-run --Werror --style=file"
