name: check

on:
  workflow_run:
    workflows: [prepare]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
        image: ghcr.io/siskapavel/oraclelinux:9
    steps:
      - run: echo ${{ env.REGISTRY }}
      - uses: actions/checkout@v3
      - name: Check clang-format
        run: find . -type f -regextype posix-egrep -regex '.*.(hpp|cpp)$' -print0 | xargs -0 clang-format --dry-run --Werror --style=file