name: prepare

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  docker-image-ol9: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_LOGIN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: 
          ghcr.io/${{ github.actor }}/oraclelinux:ol9
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            OS_DISTRO=oraclelinux
            OS_RELEASE=9
        push: true
        tags: ghcr.io/siskapavel/oraclelinux:ol9
        cache-from: type=gha
        cache-to: type=gha,mode=max
  docker-image-ol8: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_LOGIN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: 
          ghcr.io/${{ github.actor }}/oraclelinux:ol8
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            OS_DISTRO=oraclelinux
            OS_RELEASE=8
        push: true
        tags: ghcr.io/siskapavel/oraclelinux:ol8
        cache-from: type=gha
        cache-to: type=gha,mode=max
  docker-image-rl8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_LOGIN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: 
          ghcr.io/${{ github.actor }}/rockylinux:ol8
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            OS_DISTRO=rockylinux
            OS_RELEASE=8
        push: true
        tags: ghcr.io/siskapavel/rockylinux:ol8
        cache-from: type=gha
        cache-to: type=gha,mode=max
  
  docker-image-fedora39:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_LOGIN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: 
          ghcr.io/${{ github.actor }}/fedora:39
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        build-args: |
            OS_DISTRO=fedora
            OS_RELEASE=39
        push: true
        tags: ghcr.io/siskapavel/fedora:39
        cache-from: type=gha
        cache-to: type=gha,mode=max


  test_stage:
      runs-on: ubuntu-latest
      needs: docker-image-ol9
      container:
        image: ghcr.io/siskapavel/oraclelinux:ol9
      steps:
      - uses: actions/checkout@v3
      - name: Check clang-format
        run: find . -type f -regextype posix-egrep -regex '.*.(hpp|cpp)$' -print0 | xargs -0 clang-format --dry-run --Werror --style=file
  build_stage:
      runs-on: ubuntu-latest
      needs: test_stage
      container:
        image: ghcr.io/siskapavel/oraclelinux:ol9
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: autoreconf
        run: autoreconf -i
      - name: configure
        run: ./configure --with-raw --with-pcap
      - name: make
        run: make
      - name: make rpm
        run: make rpm
        


